version: "3.3"

services:
  wcdb:
    image: mysql:latest
    ports: [3306:3306]
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: wc_db
    volumes:
     - ./db_persistent_data:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3-management
    ports: [5672:5672, 15672:15672]
